### ISSUE TITLE
Using "0" (zero) as a numeric prop value results into no CSS

### ISSUE THREAD

**Issue by kettanaito** [kettanaito/atomic-layout#100]
## What:

```jsx
<Composition margin={0} />
```

Results into no `margin` CSS property being output into CSS. The same relates to any other numeric property that has `0` as its value.

## Why:

`0` is treated as a fasly value and produces no expected CSS property value.

## Environment:

- atomic-layout version: `0.6.0`

## Expected behavior:

Zero as a value results into `0` as a value of the respective CSS property: `margin: 0;`

**Comment by d1vyanshu** [comment]
Hi! I am interested in solving this bug. Can you guide me a little as where the problem is and other things

**Comment by kettanaito** [comment]
Hello, @d1vyanshu.

Thank you for deciding to help!
I believe it's a simple issue when zero is treated as a falsy value (wrong condition). I would start looking here:

https://github.com/kettanaito/atomic-layout/blob/72de75189bf28c43c7ad88fb67f0a034dece0aa0/src/utils/math/transformNumeric.ts#L3-L6

Please, if you will have an opportunity to fix it and verify it in some of the Storybook stories, feel free to issue a pull request so we can review and merge the fix.

**Comment by kettanaito** [comment]
I would suggest to check if the `value` is set.
