### ISSUE TITLE
Specify correct "styled-components" peer dependency

### ISSUE THREAD

**Issue by kettanaito** [kettanaito/atomic-layout#107]
## What:

The version format of the current `styled-components` peer dependency is invalid.

https://github.com/kettanaito/atomic-layout/blob/31d4975ec9c397550ebbdf4c2b211b2f202a75ff/package.json#L54-L57

## Why:

Installing `atomic-layout` via any package manager produces the invalid peer dependency error.

## Environment:

- atomic-layout version: `0.6.2`

## Steps to reproduce:

* Install `atomic-layout` package
* See the invalid peer dependency error in the terminal

## Expected behavior:

Installing `atomic-layout` package doesn't produce any errors.

**Comment by redraushan** [comment]
Hi @kettanaito,

I am getting following warning while adding the package from yarn:

```
yarn add v1.10.1
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
warning " > styled-components@4.1.3" has unmet peer dependency "react-dom@>= 16.3.0".
```

Is this concerned issue?

**Comment by kettanaito** [comment]
Hi, @redraushan,

well, partially. Atomic layout works properly with both v3 and v4 of `styled-components`, but the last one required the latest major version of React as its peer dependency.

I would say it isn't the library's issue. A developer has two options:

* Use `styled-components@3.x` and `react@15.x`
* Use `styled-components@4.x` and `react@16.x`

Both options are valid for Atomic layout to function properly. Mixing them is not advised, as it may cause undesired behavior in peer dependencies.
