### ISSUE TITLE
Docs - Prop aliases - Dimensions - minHeight and minWidth - Add

### ISSUE THREAD

**Issue by lokhmakov** [kettanaito/atomic-layout#110]
## What:

Add to https://redd.gitbook.io/atomic-layout/fundamentals/prop-aliases#dimensions

**Comment by kettanaito** [comment]
Thanks, @lokhmakov.

I've added the next prop aliases that were not documented:

* `minHeight`
* `maxHeight`
* `minWidth`
* `maxWidth`

The changes should be live now.
