### ISSUE TITLE
Support grid-auto-* prop aliases

### ISSUE THREAD

**Issue by innerdaze** [kettanaito/atomic-layout#130]
## Why:

Because they're missing 😄

## How:

Implement:
- autoFlow: grid-auto-flow
- autoRows: grid-auto-rows
- autoColumns: grid-auto-columns

**Comment by kettanaito** [comment]
Thank you for the suggestion. Will do.

**Comment by kettanaito** [comment]
Merged. Will be released under `0.7.1`.

**Comment by kettanaito** [comment]
It looks we overlooked the integration test for `autoFlow`, and the default assertion failed.

Fixed under https://github.com/kettanaito/atomic-layout/commit/bb3dd43134d5de2feccfe41f96f2543d70e251d2.
