### ISSUE TITLE
[RFC] Generic viewport-based API

### ISSUE THREAD

**Issue by kettanaito** [kettanaito/atomic-layout#132]
## What

I propose to expose the API that automatically assigns the given value at the given breakpoint based on a prop name's suffix (which makes a responsive prop).

## Why

So that developers can create *any* responsive logic while being inline with the defined global breakpoints.

## Specification

1. The library exports a functional utility that produces breakpoint-based values from the given configuration:

```jsx
import { useResponsiveValue } from 'atomic-layout'

const value = useResponsiveValue({
  xs: 'value when on xs',
  md: 'value when on md',
}, 'default value, when neither')
```

2. The utility function's signature is as follows:

```ts
const useResponsiveValue = <T>(breakpointMap: Record<string, T>, defaultValue?: T) => T
```

3. The utility function analyzes the given breakpoint names from the Layout options, and finds the key-value pair which breakpoint is matched by the viewport.
3. In case viewport doesn't match any of the given breakpoints, `defaultValue` is returned, if present.

3. > (?) Support for custom breakpoint objects, not defined in the Layout options.

**Comment by cdomigan** [comment]
Would this mean that I could declare a breakpoint based on the _container's_ (not the device's) height or width? I am unsure how to do this currently...

**Comment by kettanaito** [comment]
Hello, @cdomigan.

No, this issue is about to provide an API for the end developer to base *any* value or logic on the existing breakpoints you define in `Layout.configure({ breakpoints {...} })`. It mainly aims to unify implementations to be able to refer to breakpoints from anywhere, not only from [Responsive props](https://redd.gitbook.io/atomic-layout/fundamentals/responsive-props).

The feature you're describing looks like #1. Breakpoints based on containers (also called container/element queries) are possible with third-party libraries, but are not supported in CSS spec. One of the key features of Atomic layout was supposed to be Element queries, yet we need to find a siutable implementation (ideally, from CSS spec directly), not to rely on experimental technologies.

**Comment by cdomigan** [comment]
Thanks @kettanaito, and thank you for this fascinating library! What was your inspiration for converting css grid areas into React components? I haven't seen it done like that before :-)

**Comment by kettanaito** [comment]
Thank you for the kind words, @cdomigan!

I am a big fan of [Atomic design](http://bradfrost.com/blog/post/atomic-web-design/), and I happened to spot a similarity between elements composition (atoms > molecules > organisms > ...) and CSS Grid areas. Upon further investigation it appeared clear that keeping composition declaration in an abstract template string is great for reusability and maintainance. In short, that's how Atomic layout was created.

There are many other aspects that Atomic layout encourages now, and the most important of them is CSS Grid itself. Read about it, and use it alongside this library, or standalone—it's a great piece of spec.
