### ISSUE TITLE
Only: Support "visible" modifier

### ISSUE THREAD

**Issue by kettanaito** [kettanaito/atomic-layout#134]
## What:

I propose to support the `visible` prop on the `Only` component.

When provided, this prop would tell the `Only` component to render but *hide* its children, instead of conditionally rendering them.

## Why:

This would allow more control over the rendering behavior, and would solve potential nodes mismatch issues during SSR (#117).

## How:

It's tricky, since I feel that adding this prop to the current component may complicate it too much. Introducing a separate component, or splitting them into different component. Needs discussion.

**Comment by bitttttten** [comment]
What about something like `Hide`? It would always render it's children, and controls when they should be hidden from view.

```js
  <Hide from="md">
    <p>Doesn't display on md and lg.</p>
  </Hide>
```

It has the same api syntax as Only, although it would function oppositely—which could or could not be very confusing! E.g. Hide's `from<x>` hides from x and up, where as Only's `from<x>` renders from x and up.

**Comment by kettanaito** [comment]
I like the thought of introducing a new component for this use case, but you are right that the similar API but opposite functionality is confusing. Why not `<Visible from="md"/>` instead (positive namespace)?

**Comment by bitttttten** [comment]
That works too :p

**Comment by bitttttten** [comment]
I can tackle this, although I can only start next weekend.

**Comment by kettanaito** [comment]
That would be a pleasure, @bitttttten! No worries, there are no deadlines, just a matter of getting things done in a proper way. I'm quite busy at work at the moment, but I will try my best assisting in code review.

**Comment by bitttttten** [comment]
Sounds good!

I was thinking about a hook too, one that uses the MediaQueryList object. It's easy to clean it up so since it exposes a `removeListener` method.

However, since this component is to ensure that the server and client bundles match, a second option would be to look into always rendering the component and generating a media query. This would make sure there are no issues on hydration.

```js
const Visible = ({ from, display = 'block' }) =>
 styled.div`
    display: none;
    @media (max-width: ${mappings[from]}) {
      display: ${display};
    }
  `;

..

<Visible from="md" display="flex">..</Visible>
```

**Comment by kettanaito** [comment]
I highly suggest you to look into how [MediaQuery](https://github.com/kettanaito/atomic-layout/blob/master/src/components/MediaQuery.tsx) component is implemented currently. That may be of some help, for example we can extract its parts into a hook and reuse it for both components.

I think if we grab the flag from the hook, we can reuse its value in styled-component's template string directly, instead of constructing an actual media query:

```jsx
const StyledVisible = styled.div`
  visible: ${({ shouldRender }) => shouldRender ? 'visible' : 'hidden'};
`

const Visible = (...) => {
  const shouldRender = useMediaQuery(...)
  return <StyledVisible shouldRender={shouldRender} />
}
```

**Comment by kettanaito** [comment]
This looks like a good article exploring the issue of server-side rendering conditional content: https://nikitakirsanov.com/en/blog/adaptive-layout-in-react-apps-with-ssr/

Should definitely read to draw a proper conclusion on this issue.

**Comment by kettanaito** [comment]
Having read the article mentioned above, I have a few new questions to tackle during the `<Visible>` component implementation.

#### Should the conditional children have `visibility:hidden` or `display:none`, when they must not be rendered?

Both options have their benefits:

* `visibility:hidden` preserves the space taken by the children, therefore, prevents any layout jumps during hydration. This is _also its drawback_, since I may have a `<Visible to="sm">` scenario, which would result into elements taking place both when they should (xs, sm), and when they shouldn't (md, lg, xl). Do you think this is an expected behavior, @bitttttten?

* `display:none` makes the children take no actual space on the page, and may result into layout jumps. Example: `<Visible from="md">`, which would result into children not taking any place during SSR (assuming SSR uses mobile as default), and then suddenly appearing with hydration on desktop (since the screen equals, or is higher than "md").

#### Should initial match be true or false, by default?

Components that provide conditional rendering must assume the default value. At the moment the `Only` component assumes that the screen does _not_ matches the query, so the children are never rendered (you can parametrize this via props). What should the `Visible` component assume?

**Comment by bitttttten** [comment]
Hi!

Sorry for the late reply, I am a bit swamped and pushed this to the side so much I forgot about it. I don't think I'll be able to take it up soon, but I am happy to chat about it :)

I would vote for `display: none`. I would want the element completely removed, like a menubar for the navigation on mobile or extra content/text on desktop. These do not need to take space on their respectively hidden viewport. This is the behaviour I would expect 🤔  Perhaps there are use cases I am not thinking about, although I can only think of cases where I want the content hidden completely.

I also see it used in the w3 spec: https://html.spec.whatwg.org/#hidden-elements :, )

**Comment by kettanaito** [comment]
@bitttttten, worry not! Your involvement is highly appreciated, and I've started with the implementation that will be a part of #250 (next minor release).

`display:none` is viable, if you don't mind the jump. Ideally, it would be nice to specify which of the two behaviors you want: visually hidden, but taking space, or entirely not visible.

**Comment by bitttttten** [comment]
Personally I wouldn't mind the jump, as it happens when the viewport width changes so you would expect the layout to change. It wouldn't jump by itself.

I use the `display: none` technique when making my own responsive layouts so that's why I would go for it :)

Perhaps you could add a prop for it?

```js
<Visible variant="hide" />
<Visible variant="remove" />
```

Where `hide` uses visiblity none, and `remove` uses display none? The default being `remove`?
