### ISSUE TITLE
Add license

### ISSUE THREAD

**Issue by kettanaito** [kettanaito/atomic-layout#138]
This library should have a suitable license attached. The license should properly manage copyrights, commercial and uncommercial distribution, and rights of the contributors.

I'm not blindly following any "popular" licenses, because I generally like to understand what I do. That applies to choosing the license as well.

Please elaborate on which license can be suitable for Atomic layout in the comments.

**Comment by Vidlec** [comment]
You can even [go full comunism!](http://www.wtfpl.net/)
