### ISSUE TITLE
Export default options

### ISSUE THREAD

**Issue by kettanaito** [kettanaito/atomic-layout#147]
## What:

I suggest to export the default options from the `atomic-layout` module.

## Why:

To allow end developers to use the default options for the purpose of extension, or other intents.

## How:

- [ ] Scope the default breakpoints map
- [ ] Export as a named export `defaultOptions` from the `atomic-layout` module

**Comment by kettanaito** [comment]
Atomic layout options can be accessed through:

```js
import Layout from 'atomic-layout'

console.log(Layout.options)
```

It's debatable whether this reference is comfortable, but it's present as of now. It's possible to access all the options, and base your logic around them.

**Comment by greatwitenorth** [comment]
I'm using `v0.16.2` and it seems like `Layout.options` return undefined. I'm currently trying to keep all the defaults the same except for changing the min width of the xl size:

```js
  useEffect(() => {
    let options = Layout.options;
    options.breakpoints.xl = {minWidth: '1600px'}
    Layout.configure(options)
  }, [])
```

Is there a better way to do this?

**Comment by kettanaito** [comment]
Hey, @greatwitenorth. Thanks for raising this.

Since the package has migrated to be a monorepo the default layout options initialization has moved to the `@atomic-layout/core` package in order to be reused between multiple style-dependent solutions (`atomic-layout` and `@atomic-layout/emotion` at the moment). 

To access the default layout options use:

```js
import { defaultOptions } from '@atomic-layout/core'
```

To achieve the logic you've posted above:

```js
const options = Object.assign({}, defaultOptions)
options.breakpoints.xl = { minWidth: '1600px' }
Layout.configure(options)
```
