### ISSUE TITLE
Namespace collision between grid areas components and custom component

### ISSUE THREAD

**Issue by kettanaito** [kettanaito/atomic-layout#154]
## What:

When using render prop of Composition component it generates areas components based on `grid-template-areas`. This often leads to semantic namespaces collision with corresponding custom React components:

```jsx
import { Composition } from 'atomic-layout'
import Header from './components/Header'

const Page = () => (
  <Composition areas="header footer">
    {({ Header }) => (
      <>
        <Header><Header /></Header> // oops, collision!
      </>
    )}
  </Composition>
)
```

## Why:

* It decreases the DX with the library
* Grid areas often reflect semantics of a layout, just as actual component's names
* Polymorphic prop doesn't help, as area component's name already exists in scope in order to use polymorphic prop

**Comment by kettanaito** [comment]
# Proposal: `Area` generic component

Atomic layout can expose a generic `Area` component that would act as a single domain for rendering and mapping components to grid areas.

## Usage

```jsx
import { Area, Composition } from 'atomic-layout'
import { Header, Footer } from './components'

const Page = () => (
  <Composition areas="header footer">
    <Area name="header" as={Header} />
    <Area name="footer" as={Footer} />
  </Composition>
)
```

This also means that the value of `name` prop can be dynamic, switching _the content_ of the area, without changing the area position. This can come in handy when combined with #132:

```jsx
import { useResponsiveValue, Composition, Area } from 'atomic-layout'
import { Header } from './components'

const Page = () => {
  const areaName = useResponsiveValue({ lg: 'right' }, 'left')
  
  return (
    <Composition areas="left right">
      <Area name={areaName} as={Header} />
    </Composition>
  )
}
```

**Comment by kettanaito** [comment]
The difficulty with the isolated area component is to make it follow the conditional declaration of areas (in case an area is present on certain breakpoints). It may be possible through some new dedicated API, but I need to get my head around that.

**Comment by MioQuispe** [comment]
Example of naming collisions when using it

```javascript
      <Composition
        justifyContent="center"
        alignContent="center"
        templateCols="min-content 1fr"
        paddingHorizontal="1rem"
        width="100%"
        areas={actionTileAreas}
      >
        {({ Symbol, Title, Description }) => (
          <>
            <Symbol flex paddingRight="1rem" alignItems="center">
              <ActionIcon color={icon.color} icon={icon} />
            </Symbol>
            <Title flex>
              <ActionTitle use="headline6">{title}</ActionTitle>
            </Title>
            <Description flex>
              <ActionDescription use="subtitle2">{description}</ActionDescription>
            </Description>
          </>
        )}
      </Composition>
```

**Comment by kettanaito** [comment]
## Proposal: Dedicated default area

`Composition` component exposes a hard-coded default area in the render prop. That area component can be used to render other template areas parametrically without explicitly rendering their respective components.

## Usage

```jsx
const { Composition } from 'atomic-layout'
import Logo from './logo.svg'

const Header = () => (
  <Composition areas="logo menu actions">
    {({ Area, Menu }) => (
      <>
        {/* Renders "logo" area parametrically */}
        <Area name="logo" marginRight={10}>
          {/* Well, looks like no namespace collision */}
          <Logo />
        </Area>

        {/* Renders "menu" area as usual */}
        <Menu>{...}</Menu>

        <Area name="actions">{...}</Area>
      </>
    )}
  </Composition>
)
```

## Benefits

* No namespace collision between custom namespaces and areas components.
* Retaining `Composition` context, as the default `Area` component is exposed and rendered within the respective parent Composition component.

## Drawbacks

* The namespace of a default generic `Area` component is always taken, meaning you cannot have your custom area named `areas="area"`.
* `Area` namespace may also overlap with other custom namespaces, however this chance is rather small and would be an edge case

**Comment by MioQuispe** [comment]
> ## Proposal: Dedicated default area
> `Composition` component exposes a hard-coded default area in the render prop. That area component can be used to render other template areas parametrically without explicitly rendering their respective components.
> 
> ## Usage
> ```js-jsx
> const { Composition } from 'atomic-layout'
> import Logo from './logo.svg'
> 
> const Header = () => (
>   <Composition areas="logo menu actions">
>     {({ Area, Menu }) => (
>       <>
>         {/* Renders "logo" area parametrically */}
>         <Area name="logo" marginRight={10}>
>           {/* Well, looks like no namespace collision */}
>           <Logo />
>         </Area>
> 
>         {/* Renders "menu" area as usual */}
>         <Menu>{...}</Menu>
> 
>         <Area name="actions">{...}</Area>
>       </>
>     )}
>   </Composition>
> )
> ```
> 
> > `Area` name is a suggestion. It can be `Render`, or anything else.
> 
> ## Benefits
> * No namespace collision between custom namespaces and areas components.
> * Retaining `Composition` context, as the default `Area` component is exposed and rendered within the respective parent Composition component.
> 
> ## Drawbacks
> * The namespace of a default generic `Area` component is always taken, meaning you cannot have your custom area named `areas="area"`.
> * `Area` namespace may also overlap with other custom namespaces, however this chance is rather small and would be an edge case

How about <Area.Logo></Area.Logo>

**Comment by kettanaito** [comment]
I like that suggestions, @MioQuispe!
Which one do you think is more descriptive:

```js
<Area.Logo />
<Areas.Logo />
```

> I think listing "Areas" in plural may be more obvious that this key contains _more_ nested values.

**Comment by MioQuispe** [comment]
@kettanaito I think Area makes more sense tbh.
Like <Button.Primary /> vs. <Buttons.Primary> looks weird
It's the convention I've seen elsewhere in other libs, and it's shorter too.
If you are using it you've read the docs anyway or at least seen an example of it, so I don't think there's any risk for confusion.

**Comment by kettanaito** [comment]
To my deepest shame, the behavior we are discussing is possible to use even now. 

```jsx
<Composition areas="logo menu">
  {(Areas) => (
    <>
      <Areas.Logo>{...}</Areas.Logo>
      <Areas.Menu>{...}</Areas.Menu>
    </>
  )}
</Composition>
```

> Note how there is no spreading of the `Areas` object given as an argument to the render prop.
