### ISSUE TITLE
Hooks support

### ISSUE THREAD

**Issue by jEnbuska** [kettanaito/atomic-layout#157]

**Comment by kettanaito** [comment]
Hello, @jEnbuska.

React hooks are in mind, and I would like to ship the following hooks as a part of the library:

* [`useResponsiveValue`](#132) ([pull request](#149)). Allows to base any value/logic on defined layout breakpoints.
* [`useResponsiveProps`](#148). Allows to use [Responsive props API](https://redd.gitbook.io/atomic-layout/fundamentals/responsive-props) in any React components by proxying the given props via `useResponsiveValue`, and returning the relevant map of props based on current viewport.

We may also consider `useMediaQuery` hook to resolve a given media query and return a boolean, if that is practical. In case of common usage of Composition component, I don't think any hooks are applicable there (discussable, of course).

**Comment by kettanaito** [comment]
I'm open to suggestion on what may make a good hook from the library's side :) Please feel free to voice your opinion.

**Comment by kettanaito** [comment]
Please track the status of the hooks in the following issues:

* #132 
* #148

## Release

I plan to release the next React hooks in the next minor version `0.8.0`:

* `useViewportChange`
* `useBreakpointChange`
* `useResponsiveValue`
* `useResponsiveProps`

Refer to the release notes, once completed, to learn more about the functionality of the mentioned hooks. Thanks.
