### ISSUE TITLE
Down behavior works not correct

### ISSUE THREAD

**Issue by dandelionadia** [kettanaito/atomic-layout#212]
When I written maxWidthDown="300px" it is for one pixel smaller than needed. 
It is started change at 575px not at 576px.

**Comment by kettanaito** [comment]
Hello, @dandelionadia. Thank you for reaching out.

I will verify the issue and provide a fix in the next patch release. Stay tuned.

**Comment by kettanaito** [comment]
I believe the root of the issue with this calculation lies here:

https://github.com/kettanaito/atomic-layout/blob/d9e9e257570944dedee7e01b60cd0abcb26f6241/src/utils/breakpoints/closeBreakpoint/closeBreakpoint.ts#L28-L38

Perhaps in ceratin cases subtracting 1 makes sense, while when used with the CSS `@media` query it doesn't:

```css
/**
 * Consider "smDown" behavior, where 
 * { sm: { maxWidth: 768 } }
 */
@media (max-width: 767px) { /* 768 - 1 */
  /* This will not be applied on "767px" while it's still an SM breakpoint */
}
```

**Comment by kettanaito** [comment]
I've added an end-to-end test covering this scenario, but I couldn't reproduce your issue, sorry. I would suggest to look into your code, maybe something external is affecting the way your component renders. 

Please feel free to write here your investigation. Thanks.
