### ISSUE TITLE
alignContent prop doesn't apply styling

### ISSUE THREAD

**Issue by MioQuispe** [kettanaito/atomic-layout#217]
As you can see in the example, it applies no styling. if you do it manually however it works.

https://codesandbox.io/s/kind-hellman-poe4k?fontsize=14

**Comment by kettanaito** [comment]
Thank you for submitting this issue, @MioQuispe!

I can confirm that this is indeed a bug, as I can reproduce this behavior on both remote sandbox and local unit tests. Investigating further. Will update this thread once I have more technical insights.

**Comment by kettanaito** [comment]
The reason for this issue is that the `alignContent` prop alias does not exist in the prop aliases map:

https://github.com/kettanaito/atomic-layout/blob/c1ca3bd91188a787c993f77bc4cc93b3716095ce/src/const/propAliases.ts#L100-L111

Once added, I can see the unit test performed for it as well.

**Comment by kettanaito** [comment]
**The fix has been published under the version `0.9.8`.**

Please update and the issue should be gone. Let me know, if anything.
