### ISSUE TITLE
Debounced handlers re-created on each render

### ISSUE THREAD

**Issue by kettanaito** [kettanaito/atomic-layout#229]
## What:

When using `debounce()`, we are not wrapping it in `useRef()` to preserve debounced function's identity. This is an issue, as it effectively cancels any debounce at place.

## Why:

Lack of knowledge about debounce usage in functional React components.

## Environment:

- atomic-layout version: `0.9.x`

## Area of effect:

https://github.com/kettanaito/atomic-layout/blob/a76a2bf55303fc7b462beffb6065427c8045e281/src/hooks/useViewportChange.ts#L12

**Comment by silltho** [comment]
@kettanaito I would love to help you with this issue.
