### ISSUE TITLE
Event listener leak in responsive hooks

### ISSUE THREAD

**Issue by kettanaito** [kettanaito/atomic-layout#232]
## What:

It appears that all of the responsive hooks are subjected to the following issue:

<img width="1918" alt="Screen Shot 2019-10-05 at 12 10 09" src="https://user-images.githubusercontent.com/14984911/66253473-17e55a80-e769-11e9-9b6a-5f1b441aefcb.png">

This needs investigation and fix.

## Why:

Most likely the event listeners established in the hooks are not cleaned up properly when a component unmouts.

## Environment:

- atomic-layout version: `0.9.8`

## Steps to reproduce:

1. Open any story in Storybook under the "Other > Hooks" group.
1. Play around with the hook.
1. Switch to another hook story.
1. Try to resize the window. See the aforementioned error message in the console.

## Expected behavior:

- Event listeners are cleaned up after a component's unmounting
- No such error message in the browser's console

**Comment by iwgx** [comment]
Hi, do you mind if I would take this? :smiley:

**Comment by kettanaito** [comment]
Hi, @iwgx. Sure thing! I've had a quick look on your pull request and it looks great. If you don't mind I've asked you to share a little more of the technical insights of the reason for this issue. Looking forward to it being merged!
