### ISSUE TITLE
It looks like <Only> is broken! ¯\_(ツ)_/¯

### ISSUE THREAD

**Issue by dandelionadia** [kettanaito/atomic-layout#234]
When I  wrap `<Thumbnail>` with `<Only>` hover is broken.  When I hover, the component jumps.

```js
const areasFull = `
	icon thumbnail content meta
	/ auto auto 1fr
`

const areasPlain = `
	icon content meta
	/ auto 1fr
`

const Song = ({
  imageUrl,
  title,
  duration,
  artist,
  onPlayClick,
  isActive,
  isPlaying
}) => {
  const [isHover, setIsHover] = useState(false)
  const PlayIcon = getIcon(isHover, isActive, isPlaying)

  return (
    <Composition
      template={imageUrl ? areasFull : areasPlain}
      gap={1}
      alignItems="center"
      onMouseEnter={() => setIsHover(true)}
      onMouseLeave={() => setIsHover(false)}
      as={StyledSong}
      isHover={isHover}
      isActive={isActive}
      paddingVertical={0.8}
      paddingHorizontal={1}
    >
      {({ Icon, Thumbnail, Content, Meta }) => (
        <>
          {imageUrl && (
	     <Only from="md">
	         <Thumbnail>
                    <StyledThumbnail
                        src={imageUrl}
                        alt={title}
                        onClick={onPlayClick}
                    />
               </Thumbnail>
	    </Only>
          )}
        </>
      )}
    </Composition>
  )
}

export default Song
```

**Comment by kettanaito** [comment]
Thanks for reporting this, @dandelionadia!

I've checked on the issue and it looks that it's valid. Whenever `Only` component is rendered conditionally, each of its mounts appear as debounced (although I haven't found any actual debouncing/throttling at place in the code). Needs more. investigation.

**Comment by kettanaito** [comment]
It looks that the issue has been in the usage of `useEffect` in the `<MediaQuery/>` component (`useMediaQuery` hook in the future releases). When replaced with `useLayoutEffect` the staggered re-rendering (jumping) is gone. Expect this to be fixed in the next minor release.

**Comment by kettanaito** [comment]
This issue has been fixed and will be released in `0.11.0`.

**Comment by kettanaito** [comment]
As of `0.12.2` this should be fixed. @dandelionadia, please, let use know if the issue still persist after you update the library. Thanks.

**Comment by kettanaito** [comment]
Hi, @dandelionadia. Could you please double check this behavior in your project after updating to `atomic-layout@0.12.6`?

I was working on a related issue and would like to make sure this one stays fixed. Thank you.

**Comment by dandelionadia** [comment]
All is well.
