### ISSUE TITLE
using percentage unit in prop-aliases

### ISSUE THREAD

**Issue by ruhaise** [kettanaito/atomic-layout#235]
sometimes it is necessary to use percentage as unit in prop-aliases,

for example this wont work
```
<Box padding={10%}> Foo </Box>
```
we might have px or rems as default unit but it is good to allow % as extra unit, 

even if planning to implement the % unit, it is only applicable to certain prop-aliases like padding, margin etc.. 

still not sure if it is worth the effort or how easy to implement it ?

**Comment by kettanaito** [comment]
Hi, @ruhaise. That's a good question.

All measurement units may be useful depending on your use case. That includes percentages. To use any measurement unit different from the one you set as the default one (equals to "px" by default, can configure through `Layout.configure()`), provide it as a string value:

```jsx
<Box padding="10%" />
```

> This concerns em/rem, percentages, vh/vw, in, and any unit you can find in the CSS specification.

The recommended strategy is choose a measurement unit you use the most, and set it as [the default measurement unit](https://redd.gitbook.io/atomic-layout/api/layout/configure#defaultunit) of your layout. You can always pass another unit by explicitly wrapping the value in a string.

Hope that helps!

**Comment by ruhaise** [comment]
i couldnt find this information in documentation, thanks :) that helps

**Comment by kettanaito** [comment]
You are right, this info is not directly communicated in the docs. I'd expect this to be in "Prop aliases" section, but it can also reside in its own section (i.e. "Handing prop values").

**Comment by ruhaise** [comment]
@kettanaito  i will try to add this to the docs :)
