### ISSUE TITLE
Fix "repository" and "homepage" in "package.json"

### ISSUE THREAD

**Issue by kettanaito** [kettanaito/atomic-layout#266]
Mentioned fields lead to 404 pages on GitHub.

**Comment by ruhaise** [comment]
@kettanaito found the missing `repository` links, but cant find the homepage feild at all

**Comment by kettanaito** [comment]
@ruhaise That's my bad, I don't think `homepage` is set. I wasn't sure which field NPM uses on their pages, so I assumed both. 

If you'd like to tackle this, please make sure `repository` points to the proper directory location in Git tree. At the moment it results into 404 page.

## Steps to reproduce

1. Open `atomic-layout` on NPM
1. Click on its "Repository` link

**Comment by ruhaise** [comment]
@kettanaito im on it, NPM uses just `repository` field

**Comment by ruhaise** [comment]
this https://github.com/kettanaito/atomic-layout/pull/268 should close this issue

**Comment by kettanaito** [comment]
@ruhaise thanks for involvement! Got it approved and merged. Will be live in the next release.
