### ISSUE TITLE
CI pipeline doesn't run for repository forks

### ISSUE THREAD

**Issue by ruhaise** [kettanaito/atomic-layout#269]
## What:

CI pipeline doesn't run when doing a pull request from a forked repository

## Why:

I don't know exactly why it is like this, perhaps something wrong in the CI config needs more investigation

## Environment:

- node vesrion: `v12.xx.x`
- npm version: `6.xx.x`

## Steps to reproduce:

1. fork the repo
2. do your changes in the forked repo
3. create a PR to master
4. the CI pipeline does not run

## Expected behavior:
I believe in any scenario the pipeline should run, I might be wrong

## Screenshots:
example screenshot for a recent PR I have done

![image](https://user-images.githubusercontent.com/25627383/71446823-01c3b680-2728-11ea-9467-9937da16e980.png)

**Comment by ruhaise** [comment]
@kettanaito what do you think about this issue?

**Comment by kettanaito** [comment]
A valid points. I've always thought its how CI works with forked repositories, but after a little research I found [this](https://circleci.com/docs/2.0/oss/#build-pull-requests-from-forked-repositories). 

**Update:** "Build forked pull request" is now enabled in the CircleCI. Any new pull requests should have proper CI status reported directly to the repo. Consider this closed.
