### ISSUE TITLE
Update contributing docs to reflect monorepo structure

### ISSUE THREAD

**Issue by ruhaise** [kettanaito/atomic-layout#274]
## What:
After migrating to mono-repo structure the development guidelines is not updated,

## Why:
I think it's a good idea to keep the development guidelines updated, it can make the process easier for someone new to the project

**Comment by ruhaise** [comment]
@kettanaito im not sure if its necessary

**Comment by kettanaito** [comment]
A valid point. After migrating to the monorepo structure there are a few changes to the development process of the library and I'd like to reflect those in the Contributing guidelines. 

## List of updates

1. Bootstraping the monorepo (using `yarn`)
1. Short example of how to add a new dependency to a specific package.
1. Workflow example for a specific package. Notice that there is no need to link a dependency which is a sibling package in the same monorepo.
1. Adjustments to the testing process (mainly that you need to change CWD and proceed with testing as written currently).

Maybe it would make sense to create a separate sections for contributing to the core repository and rendering repositories, to highlight the conceptual difference between those. That would be an addition to the existing guidelines.
