### ISSUE TITLE
README is broken on NPM

### ISSUE THREAD

**Issue by kettanaito** [kettanaito/atomic-layout#277]
## What:

NPM states that `atomic-layout` package doesn't have a README.

## Why:

Due to the monorepo structure.

## Environment:

- atomic-layout version: `0.12.3`

## Steps to reproduce:

1. Go to https://www.npmjs.com/package/atomic-layout
2. See the following message instead of README:

```
"Unable to find a readme for atomic-layout@0.12.3"
```

## Expected behavior:

`atomic-layout` package on NPM displays the current README from the repository.

## Screenshots:

<img width="643" alt="Screen Shot 2019-12-30 at 12 57 48" src="https://user-images.githubusercontent.com/14984911/71581097-01e6fc00-2b04-11ea-80ab-9d3d7725474d.png">

**Comment by ruhaise** [comment]
@kettanaito i think to solve this we should have a copy of `README.md` in `https://github.com/kettanaito/atomic-layout/tree/master/packages/atomic-layout` as well, is it correct ?

**Comment by kettanaito** [comment]
Perhaps, let's see if we can achieve that with symlinks? NPM should support that.

**Comment by ruhaise** [comment]
@kettanaito this seems fixed the issue, but I'm still not sure if this is the correct approach?
now the `README.md` is moved to the `packages/atomic-layout` then i have added a symlink from it to the root of repository just for GitHub, now the npm will find the`README.md` from the package

**Comment by kettanaito** [comment]
@ruhaise We need to make sure the root-level README is not broken on GitHub. I think we should preserve the root-level and symlink it to `packages/atomic-layout`. Would that work in your opinion?

**Comment by ruhaise** [comment]
@kettanaito  that should work as well, atleast in github im sure, but im not sure about npm, i did some research and was not able to find any proper documentaion about it

**Comment by ruhaise** [comment]
@kettanaito I have pushed the changes as you proposed, but i have no clue how to test this without publishing

**Comment by kettanaito** [comment]
Thanks for the update! Looks much better.

If you open the [`packages/atomic-layout`](https://github.com/kettanaito/atomic-layout/tree/277-broken-README.md/packages/atomic-layout) you can see that the symlinked README has broken images. That is because the paths to the assets are relative to the root directory. This one is an interesting to solve. I'd suggest looking to other monorepo packages and how they handle README in their repository.

**Comment by ruhaise** [comment]
@kettanaito  I made the broken links from relative to absolute this seems fixed the issue, but I'm not sure if this is the right way. did a bit of research and couldn't find a better solution.

**Comment by ruhaise** [comment]
@kettanaito  what is the status of this issue? seems like the PR fixed it right?

**Comment by kettanaito** [comment]
@ruhaise, I believe so. Sorry, I've been busy with other tasks and haven't looked at your pull request in the full extent. Will do so in the nearest future. Thank you once more for contributing!
