### ISSUE TITLE
Using a dot in area template generates an unexpected area component

### ISSUE THREAD

**Issue by brumm** [kettanaito/atomic-layout#287]
Using a dot in area template generates an area component for `.`.
I'd expect this not create a component, because the period is not its own area, it's a discontinuation of the neighboring area.

**Comment by kettanaito** [comment]
Hi, @brumm. Thanks for reporting this!

Indeed, that sounds unexpected. There is a utility function called `sanitizeTemplateString` that is responsible for removing all the unnecessary details from the template declaration (i.e. indentation, inline row/column dimensions in case of `grid-template`).

https://github.com/kettanaito/atomic-layout/blob/43373e6436c91c9b821a338a5290851003fc2b99/packages/atomic-layout-core/src/utils/strings/sanitizeTemplateString/sanitizeTemplateString.ts#L6-L28

During one of its iterations it asserts that a given chunk of a template is a valid area name:

https://github.com/kettanaito/atomic-layout/blob/43373e6436c91c9b821a338a5290851003fc2b99/packages/atomic-layout-core/src/utils/strings/isAreaName/isAreaName.ts#L1-L10

Perhaps, an easy fix would be to add a dot (`'.'`) into the `keywords` list, so its occurrence is not treated as an actual area name, but something to safely skip. We would need at least a new unit test suite for `isAreaName` to assert this.

Please, would this be something you are interested in fixing?

**Comment by kettanaito** [comment]
According to the [Naming Things In CSS Grid Layout](https://www.smashingmagazine.com/2017/10/naming-things-css-grid-layout/) article by Rachel Andrews, CSS Grid can also accept an arbitrary sequence of dots (".") followed by each other to use as a placeholder.

We must handle this as well. Perhaps, make the `keywords` list include both strings and regular expression, and perform an `exp.test()` if an expression is met inside the `isAreaName` function.

**Comment by kettanaito** [comment]
The fix has been merged. Please update to `atomic-layout@0.12.5` and let me know if it's okay now. Thank you.
