### ISSUE TITLE
I can't attach a ref to Composition, because Composition does not use React.forwardRef

### ISSUE THREAD

**Issue by brumm** [kettanaito/atomic-layout#297]
## What:

Attaching a ref to Composition results in a warning:

`Warning: Function components cannot be given refs. Attempts to access this ref will fail. Did you mean to use React.forwardRef()?`

## Why:

Composition does not use React.forwardRef
- atomic-layout version: `^0.13.0-alpha.2`

**Comment by kettanaito** [comment]
Hi, @brumm. Thanks for reporting this!

You're right, `Composition` (and I think `Box`, and `Only`) component does not forward refs 😧Should be fast to fix by introducing `React.forwardRef`. 

Please, would you mind issuing a pull request? I'll gladly assist in code review and we'll ship the refs as they should be.
