### ISSUE TITLE
Rename "useResponsiveComponent" since it's not a hook

### ISSUE THREAD

**Issue by kettanaito** [kettanaito/atomic-layout#298]
## What:

The named export `useResponsiveComponent` should be renamed.

## Why:

Exporting functions that start with `use` in React ecosystem implies it's a [React hook](https://reactjs.org/docs/hooks-intro.html). In this case it's ambiguous, since `useResponsiveComponent` is rather a high-order component than a hook.

**Comment by ruhaise** [comment]
@kettanaito what do you propose to rename it to?

**Comment by kettanaito** [comment]
@ruhaise, I think we can adopt a spoken convention of high-order components, and name that function like `withResponsiveProps()`. That'd imply it's a HOC, and I also like the change from "ResponsiveComponents" to "ResponsiveProps", because it's more precise regarding what's going on internally in that function.

What do you think?
