### ISSUE TITLE
Rerendering of parent component causes Only to unmount and mount its children

### ISSUE THREAD

**Issue by Vidlec** [kettanaito/atomic-layout#308]
## When:
```ts
const MobileRoutes = () => {
  return (
    <Only to="md">
      <Switch>
        <Route path={Routes.PROFILE_TROPHY_DETAIL} component={TrophyDetail} />
        <Route path={Routes.PROFILE_SETTINGS} component={ProfileSettings} />
        <Route path={Routes.PROFILE_STATS} component={Stats} />
      </Switch>
    </Only>
  )
}
```

## Current behavior:

When `<MobileRoutes/>` is rerendered, it causes `<Only>` children to unmount and mount again, effectively reseting its state.

## Expected behavior:

It will just cause regular rerender, preserving state.

## Environment:

- atomic-layout version: every

## Repro
https://codesandbox.io/s/sleepy-hugle-u6036

**Comment by Vidlec** [comment]
As you can see in the sandbox. Changing parents state causes Only's children to loose its state

**Comment by Vidlec** [comment]
Workaround is to wrap `<Only>` with component wrapped in `memo`

**Comment by kettanaito** [comment]
Hi, @Vidlec. Thanks for reaching out with this issue. I've checked the sandbox attached, and was able to reproduce the problematic behavior you're experiencing. I'll dive into this and let you know once I found the root cause.

**Comment by kettanaito** [comment]
@Vidlec, thanks for providing a reproduction scenario. This issue is fixed.

Published:

```
 - @atomic-layout/emotion@0.12.2
 - atomic-layout@0.13.2
```

Could you please update and let me know it works properly for you now?
