### ISSUE TITLE
Export a utility to compose inline @media queries

### ISSUE THREAD

**Issue by kettanaito** [kettanaito/atomic-layout#311]
## What:

I suggest to export a utility that would behave similar to `useResponsiveQuery` and would compose an inline string media query to be used in CSS-in-JS environment.

## Why:

The current usage of inline `@media` queries is lengthy:

```jsx
@media (min-width: ${Layout.breakpoints.lg.minWidth}) and (max-width: ${Layout
    .breakpoints.lg.maxWidth}) {
  width: 65px;
}
```

## How:

```jsx
import { newUtil } from 'atomic-layout'

const Component = styled.div`
  @media ${newUtil({ from: 'sm', to: 'lg' })} {
    width: 65px;
  }
`
```

> Internally, `useResponsiveQuery` accepts the same responsive API and maps it to the list of media query strings. I think we can split `useResponsiveQuery` and export the underlying functionality publicly as well.

**Comment by vitordino** [comment]
i’ve did something similar on my [etymos](https://github.com/vitordino/etymos) library, more specific a [`above`](https://github.com/vitordino/etymos/blob/master/src/utils/above.tsx) util.. shouldn’t be so hard to adapt to this `from`/`to` behaviour — i had one of it, but as i usually only use above, i removed the `between` util at some point prior the release of the lib..

i did kept the [`useMediaQuery`](https://github.com/vitordino/etymos/blob/master/src/hooks/useMediaQuery.tsx) hook tho (supporting `above` and `below` options), and it was a render prop component before

it might help

**Comment by kettanaito** [comment]
Hey, @vitordino. Thank you for the insights.

Yes, indeed, this utility shouldn't be anything critical to implement. Especially, because there is an already published `useResponsiveQuery` React hook that accepts the "from/to" API, but instead of returning a media query string it returns a media query match (the hook is designed for conditional rendering):

https://github.com/kettanaito/atomic-layout/blob/ba295c70b79fa4e90beafc26f9fb13257c5fc55c/packages/atomic-layout/src/hooks/useResponsiveQuery.ts#L101-L109

If this logic above is put into a separate function, then it could be reused in `useResponsiveQuery`, and exported standalone for the inline media query composition, as mentioned in the issue's description.

How would you call a hook that behaves like this? I'm thinking of naming it `query`:

```jsx
import { query } from 'atomic-layout'

const MyComponent = styled.div`
  @media (${query({ from: 'sm', to: 'lg' }}) {
    font-size: 2rem;
  }
`
```
