### ISSUE TITLE
Input in a grid item loses focus due to extra parent rerendering

### ISSUE THREAD

**Issue by devmao** [kettanaito/atomic-layout#320]
## When:

1 - Open this codesandbox https://codesandbox.io/s/atom-layout-playground-5d7iu
2 - Start typing into the red text input

## Current behaviour:

At any keypress, the input loses the focus

## Expected behaviour:

The input doesn't lose the focus

## Environment:

- node vesrion: `n/a`
- npm version: `n/a`
- atomic-layout version: `0.15`

**Comment by kettanaito** [comment]
Thanks for reporting this, @devmao. I'll investigate what's wrong. I'm slightly overloaded right now, so it may take up to a week. Anybody willing to dive into this is welcome.

**Comment by kettanaito** [comment]
The issue is fixed. Published in [`0.16.1`](https://github.com/kettanaito/atomic-layout/releases/tag/atomic-layout%400.16.1).

@devmao, could you please update and confirm that? Thanks!

**Comment by devmao** [comment]
works! thank you
