### ISSUE TITLE
Creating a 3 column layout.

### ISSUE THREAD

**Issue by ZombieChowder11** [kettanaito/atomic-layout#323]
Hey,

I'm trying to create a page with a 4 column layout where the first column on the first row takes a `span 2`  and the first column on the second row takes a `span 3`. However I'm finding it a bit difficult to achieve this following the guide in the [using areas as templates](https://redd.gitbook.io/atomic-layout/api/components/composition#using-areas-templates) section.

What am I doing wrong in my `template` area or this is just not supported by _atomic-layouts_. Here is my code:

```
const templateTablet = `
  meta actions mex 
  text hex 
  / auto auto auto auto
`;

export const ClassRoom = () => (
  <Composition template={templateTablet} gap={10}>
    {Areas => (
      <>
        <Areas.Meta colStart="1" colEnd="3">
          <Card text="111" />
        </Areas.Meta>
        <Areas.Actions colStart="3" colEnd="3">
          <Card text="222" />
        </Areas.Actions>
        <Areas.Mex colStart="4" colEnd="4">
          <Card text="333" />
        </Areas.Mex>
        <Areas.Text colStart="1" colEnd="4">
          <Card text="444" />
        </Areas.Text>
        <Areas.Hex colStart="4" colEnd="4">
          <Card text="555" />
        </Areas.Hex>
      </>
    )}
  </Composition>
);

export default ClassRoom;

```

**Comment by kettanaito** [comment]
Hey, @ZombieChowder11. Thanks for asking this, I'll try to help.

First that catches my attention is that in your `templateTablet` string you have unequal number of areas and columns:

```
meta actions mex
text hex
/ auto auto auto auto
```

By specifying 4 columns (`/auto auto auto auto`) you need to make sure that your areas (meta, actions, text, hex) fill _all_ those columns. This requirement comes from the CSS Grid spec, and the proper template may look like this:

```
meta actions mex .
text hex . .
/ auto auto auto auto
```

> I've used a dot (`.`) as a [placeholder area](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Grid_Layout/Grid_Template_Areas#Leaving_a_grid_cell_empty) in the grid. This means that the associated row/column will not be taken by any areas.

However, from what you've described, using a placeholder isn't what you want. I believe the layout you want can be achieved by _repeating_ the areas you wish to span between columns:

```
meta meta actions mex
text text text hex
```

> In the template above the `meta` area takes 1 / span 3 columns, leaving `actions` and `mex` to follow in the 3rd and 4th columns respectively. The `text` area on the second row takes 1 / span 4 columns, with `hex` following in the remaining column.

Repeating an area in a `grid-template-areas` is an implicit way to specify its `grid-column-start` and `grid-column-end` (as well as similar properties for `grid-row-*`). This way you don't have to specify start/end explicitly, as well as `auto auto ...` for each column.

**Here's a [sandbox with the solution](https://codesandbox.io/s/4-column-layout-9h1w2) using the areas from the explanation above.**

In case I didn't get the position properly, try to play around with the areas repetition, I'm sure you'll get it as you need. Let me know if this answers your question.

**Comment by ZombieChowder11** [comment]
Hey @kettanaito , that does solve the problem, thanks!

**Comment by kettanaito** [comment]
Happy to hear that!
