### ISSUE TITLE
React Native support

### ISSUE THREAD

**Issue by kettanaito** [kettanaito/atomic-layout#34]
## What
Suggest to consider React Native support.

## Why
Because creating layouts in RN is a hell.

## How
- [x] Read if RN supports CSS Grid (it doesn't at the moment)
- [ ] Render native components instead of browser tags
- [ ] Test on a RN project

**Comment by MatthiasMargot** [comment]
I have never worked with react-native, have you?

**Comment by kettanaito** [comment]
I had a pet project on React Native some time ago, and one of my colleagues is working on it at the moment.

I've did a quick research, and React Native doesn't seem to support CSS Grid. There may be a feature request, however. Would be nice to have Atomic layout in good shape when that support lands. I think a lot of people would feel the difference.

**Comment by kettanaito** [comment]
React Native doesn't support CSS Grid, as it doesn't have DOM and CSS as such. CSS features support comes down to CSS interpretation used in React Native.

As of now, I don't see a reliable way to bring Atomic layout to native environment without duplicating CSS Grid spec, which would be unreasonable. However, since Atomic layout is based on CSS Grid, you are free to use any applicable CSS Grid polyfill, if there are any. Once native environment is able to render elements based on the spec, Atomic layout should work automatically.
