### ISSUE TITLE
Increase test coverage

### ISSUE THREAD

**Issue by kettanaito** [kettanaito/atomic-layout#40]
## What
Need to increase code coverage up to 100%.

## Why
To have our code covered with tests, of course. And also because 99% coverage is simply unacceptable.

## How
* See [Coveralls coverage report](https://coveralls.io/github/kettanaito/atomic-layout) to know the uncovered modules

**Comment by kettanaito** [comment]
Added unit tests for `invariant` function: a6bb2372df9fedbec288cc283274075fc1fb36bb

**Comment by Vidlec** [comment]
I was writing tests to cover missing branches and found out that in 
`src/utils/templates/getAreasList.js`
```js
      const propValue = sanitizeTemplateString(props[propName])
      const nextAreas = propValue ? res.areas.concat(propValue) : res.areas
```
propValue can be never undefined or false because `sanitizeTemplateString` always returns an array. 

So either check for array length or remove this check. 
What do you think?

**Comment by kettanaito** [comment]
@Vidlec You are completely right!

```js
[].concat(2) // [2]
// is indeed the same as
[].concat([2]) // [2]
```

Yes, we should remove that check and just concat the received sanitized template string to `res.areas`.

If you can, you can add that via pull request, that would be massively appreciated! If not, just create a ticket so we don't forget about that.

---

Also, ❤️ for increasing test coverage.

**Comment by Vidlec** [comment]
There is a one last thing to have 100% coverage
```js
if (prefix === 'min') {
      if (includesArea) {
        if (behavesSame || behavesInclusive) {
          nextValue = breakpointB[propName]
        }
      } else {
        if (shouldStretch) {
          nextValue = breakpointB[propName]
        }
      }
    }
```
That `else` branch is uncovered. I dont dare writing test for this, because I have no idea how this works 😃

**Comment by kettanaito** [comment]
@Vidlec 😄 

I think this is `mergeBreakpoints` function, isn't it?
That fires when you merge a `minABC` property of the breakpoint and the template declaration doesn't include the current area, *and* this area must be stretched. I doubt that makes the picture any cleaner for you...

I can explain you in person, just ping me anytime. It's nothing complicated, I promise.

**Comment by kettanaito** [comment]
Test coverage has increased to 100% by merging your pull request #47.

Much thanks and welcome to contributors!

**Comment by kettanaito** [comment]
@Vidlec Please let me know if we should reopen this issue to have that last branch covered. I have overlooked the comment and have already closed it. Sorry.
