### ISSUE TITLE
Lack of indentation in template breaks the Composition component

### ISSUE THREAD

**Issue by Vidlec** [kettanaito/atomic-layout#65]
## What
Lack of indentation in template breaks the Composition component

Not working
```js
const template = `
top
bottom
`
```

Working
```js
const template = `
  top
  bottom
`
```

## Why
Hard coded white space removal

## Environment
* All environments

## Expected behavior
You dont need to append whitespace to template string

**Comment by kettanaito** [comment]
Indentation now has no effect over template areas parsing.

Merged and published in the patch version `0.3.7` (011887e0667dd8dd2597a5c00bafbfc98aaa85c2).
