### ISSUE TITLE
Changing the grid template forces all areas to re-render

### ISSUE THREAD

**Issue by garth** [kettanaito/atomic-layout#84]
## What
Changing the grid template forces all areas to re-render, even if they have not changed

## Why
I would guess that the area components are being recreated instead of being reused

## Expected behavior
Existing areas should not be re-rendered.

**Comment by kettanaito** [comment]
Hi.

Could you please give me some code of how you are updating the template?
At the moment template prop updates aren't going to cause any logic. So template update doesn't trigger areas generation, and, in return, doesn't trigger their re-creation.

I would say that dynamic layout templates are not recommended. At least, I can't think of a justifiable use case for that.

**Comment by garth** [comment]
I have a new template for every route, so the template property is updated regularly, but not all areas are replace, so those that remain should not need to be re-rendered.

I have tried to look into making some fixes to the code, but unfortunately the src is using flow and the output from flow is not very close to the original.

**Comment by garth** [comment]
OK, I found the problem, actually when I first used this component it didn't update reliably when switching the template, so I put a key in there to reset it, which Is why it's now re-rendering each time. So it's my fault sorry, I will close this issue and create a new issue with the root issue.

**Comment by kettanaito** [comment]
I'm glad it was a `key` issue.

What do you mean regarding flow? There is no compilation from flow, so the code you see is the exact code you get. Do I miss something?

**Comment by kettanaito** [comment]
Yeah, I have this has to do with the module bundling, not the flow per say. I usually ship modules with `umd`, so they could be used in any module type (commonjs, es, etc.).

Anyway, if you want to try something it takes a minute to clone a repo and install its dependencies :) You would probably spend much more time trying to adjust the built dist, which isn't a good idea.
