### ISSUE TITLE
Changing the template does not render the new areas correctly.

### ISSUE THREAD

**Issue by garth** [kettanaito/atomic-layout#85]
## What
When the grid template updates some previous areas are not removed and the grid layout breaks.

## Why
?

## Steps to reproduce
update the template with a new arrangement

## Expected behavior
any changes to the existing area positions should be applied, non-existant areas should be removed.

**Comment by kettanaito** [comment]
This needs to be discussed on a conceptual level. As I have mentioned, I can't think of a sensible example where dynamic templates would make sense.

I remember your use case with routing, where you serve different template depending on the route. Have you considered something like this:

```js
function withTemplate(template) {
  return ({ children }) => (
    <Composition template={template}>
      {children}
    </Composition>
  )
}

<Router>
  <Route path="/user" render={withTemplate('first second')} />
</Router>
```

It's a pseudo-code, but the principle is that you generate a dedicated composition for each route, instead of having a single composition that adjusts to the route (updates its `template`). How would changing to this approach affect your implementation?

**Comment by garth** [comment]
I'm afraid I can't agree with your opening statement. React is specifically intended to be dynamic. Any changes to props should produce a predictable result, ideally all components should be pure.

As it turns out, I could implement everything I need from atomic layout with the following stateless component:

```tsx
import React, { ReactType, CSSProperties } from 'react'

const Grid: React.StatelessComponent<{
  className?: string
  style?: CSSProperties
  template: string
  components: { [name: string]: ReactType }
}> = ({ className, style, template, components }) => (
  <div className={className} style={{ ...style, display: 'grid', gridTemplateAreas: template }}>
    {template
      .match(/([\w])+/g)
      .filter(area => components[area])
      .map(area => {
        const Component = components[area]
        return (
          <div key={area} style={{ gridArea: area }}>
            <Component />
          </div>
        )
      })}
  </div>
)

export default Grid
```

Thanks for the inspiration.

**Comment by garth** [comment]
I would also consider to separate your concerns. For example, the responsive props could be a standalone component. And the grid a separate one. In most cases projects will only need one or the other, and if they need both then they just include both.

I already have the responsive aspects covered elsewhere in my app, so I will just pass in a different template per screen size where necessary and then the above code will do most of what atomic-layout does.

**Comment by kettanaito** [comment]
@garth, I definitely don't like that template updates are not reflected, which breaks the expectations patterns from a React component. The more I think about it, the more I am sure to implement those updates in the near future.

Regarding your separation idea, I don't think this is the call. The whole point of `Composition` is to be a single dedicated unit responsible for any kind of spacial distribution. Once you split it into different parts, not only it would increase the usage complexity, but it would also break the concept that it tries to encourage.

It's great that you can manage responsive from another point of your app, but that doesn't mean that it should necessarily remove it from the `Composition`. The biggest part of the logic of Atomic layout is focused on determining conditional areas to prevent unnecessary rendering. The areas assignment part is a rather small step, so it generally depends on your requirements.
