### ISSUE TITLE
Provide typescript definitions

### ISSUE THREAD

**Issue by Vidlec** [kettanaito/atomic-layout#87]
## What
Add typescript definitions

**Comment by kettanaito** [comment]
Thanks for suggestion. Providing type definitions is on my list, but I can't do everything by myself.

I would appreciate if you create a pull request with the basics of type definitions. Please let me know if you have time, and whether my support is needed. Thanks.

**Comment by kettanaito** [comment]
@Vidlec Could you please issue a pull request with the state you have got now?
I could review it in a spare time, to polish it together.

**Comment by kettanaito** [comment]
I would like to rewrite the entire repository in TypeScript entirely. Your contribution would be very valuable in this process, so thank you!

**Comment by kettanaito** [comment]
Quick status report: I've rewritten the entire library in TypeScript and adjusted the test cases, where necessary. Build and tests pass, and there are finally useful autosuggesting throughout Atomic layout usage 🎉

There is a response timeout on integration tests happening at the moment, which breaks CI. Working on that right now.

**Comment by kettanaito** [comment]
TypeScript support will be released in the next minor version.
