### ISSUE TITLE
Internet Explorer support

### ISSUE THREAD

**Issue by kettanaito** [kettanaito/atomic-layout#92]
In this issue I would like to elaborate on the support of Internet Explorer.

First, let me address the developers that require Internet Explorer support: I respect your decisions, and understand that one of the top priorities is satisfying the client's needs. By no means I want to show disrespect or hold a grudge against you, or any kind of technology you support. I simply want to cover how Internet Explorer support affects `atomic-layout`. Thank you.

## Insufficient partial CSS Grid spec support

Atomic layout uses CSS Grid, which is only partially supported in IE11, without any kind of support in prior versions of the browser. Upon testing, that partial support is simply not enough to provide good developer and user experience, as some vital CSS Grid properties are not implemented (***I will mention them here***). I see no point of such archaic support if it results into broken implementation anyway. I'm also against shipping extra workarounds just for the IE's sake.

## Internet Explorer is dead

Internet Explorer as project is not supported by Microsoft for years now. It still gets bugfixes, but it will not ship new features, and what interests us the most, new implementations of CSS spec.

Since you cannot use CSS Grid with IE, do not expect to use Atomic layout with IE. I believe in brighter future of web, where we don't support legacy browsers for years, but rather educate our customers to evolve alongside the web.

## Holding things down

Supporting legacy technology comes with a cost: you cannot develop things how you envision it, but need to constantly compromise to endure that support. For example, I do wish to adopt Proxy (#86) to grant much better developer experience when working with the library. With IE I simply cannot.

## Conclusion

I'm sorry for those who count on using Atomic layout in IE10-11, but I've decided to remove IE support entirely by introducing Proxies. You will not be able to use this library in the mentioned browser, so please consider an alternative, or drop the support of IE in your product, if you can.

Thank you.

**Comment by kettanaito** [comment]
After the recent research there may be a way to make your application use Atomic layout and support CSS Grid in IE. It won't be handled on the library side, but I will try to prepare an example of how you can achieve that.

**Comment by kettanaito** [comment]
As the next step, I will try to integrate `babel-plugin-styled-components-postcss` into the Babel config of the library. This way the AST transformations will be applied to the CSS emitted by the library. The tricky part would be to inherit the usage-point PostCSS config.

**Comment by kettanaito** [comment]
The usage of `babel-plugin-styled-components-postcss` doesn't solve the issue, since it's a build-time transformer. The styles that will be generated by styled-components based on the provided responsive props of Atomic layout happen in the runtime of the *usage surface* (i.e. your app). It will not hook up that Babel plugin, and it shouldn't.

The more I investigate this issue, the more I'm convinced the result is not worth the noise. At the moment I'm not going to continue investigation of IE support, since it has proven numerous times to be an extremely hacky endeavor. Please consider educating the web.

**Comment by kettanaito** [comment]
# Technical notes

For those wondering why it's not an easy task to support autoprefixing (*polyfilling* later) for style template literals in Atomic layout (to enable CSS Grid support in IE, for example), here are a few technical notes.

1. Polyfilling must happen on the end developer's side. It's not about supporting a single feature, but about an ability to transform generated CSS (or raw template strings) with whichever transformations required by the end developer.
1. Styled components have no support for transforming emitted CSS (on purpose). This makes it impossible to polyfill on the end developer's side *directly*. As Atomic layout strives to become [style-agnostic solution[(#57)], it gets harded to cope with implementation difference of each CSS-in-JS solution in terms of post-generative transformations.
1. Polyfill must reflect developer's changes. Styles generation in Atomic layout is dynamic. This means that the library itself doesn't know which styles you will configure its components to generate. Since the styles are configured by the end developer, there is no way to polyfill them at the library's build time. Build time is the only place where some Babel plugin can be put to take raw style template literals and process them through PostCSS, for example.

**Comment by brianjuhl** [comment]
@kettanaito -- Love your thought process on this!
